- become: yes
  hosts: localhost
  name: apache-install
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        update_cache: yes
        state: latest
      
    - name: Enable mod_rewrite
      apache2_module:
        name: rewrite 
        state: present
      notify:
        - Restart apache2

    - name: Create Index file
      command: /bin/echo "<h1><b>Server is running<b><h1>" > /var/www/html/index.html

  handlers:
    - name: Restart apache2
      service:
        name: apache2
        state: restarted

    - name: Enabling password login
      shell: |
        sed 's/PasswordAuthentication no/PasswordAuthentication yes/' -i /etc/ssh/sshd_config
        systemctl restart sshd
        service sshd restart
        useradd admin
        echo {{ password }} | passwd --stdin admin
        sudo usermod -aG wheel admin

    - name: Mounting EFS on /var/log
      shell: mount -t efs {{ efs_id }}:/ /var/log